### ISSUE TITLE
Add a plugin.txt entry

### ISSUE THREAD

**Issue by quyykk** [DarcyManoel/-Omnis#53]
There's a plugin.txt entry now you can use so that the plugin can be called "Omnis" in game without having to change the ~~hacky~~ folder name.

For example, this is the high dpi one: https://github.com/endless-sky/endless-sky-high-dpi/blob/master/plugin.txt

**Comment by DarcyManoel** [comment]
I'll do the plugin.txt thing because it's what the game is moving towards, also lets me tweak the displayed name to just `Omnis` instead of `-Omnis`. The current name being for the sake of load orders
